var cities = [];
var markers = [];
var paths = [];
var sessionId;
var optimalCost;
var optimalTime;
var totalCost;
var pathsToRetry = [];
var routeLabels = [];
var noOfCityRows = 0;
var directionsService;
var displayCityAjaxCalls = [];