version: '3.7'
 
services:
    sql-server:
        platform: linux/amd64
        build: 
          context: .
          dockerfile: backend/src/Infrastructure/DreamTravelDatabase/Dockerfile
        ports:  
          - "1404:1433"