# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool: Azure Pipelines
  
variables:
  BuildConfiguration: 'Release'
  ASFProjFolderName: 'src\Pyra.Csp.LicenseAssignments'

stages:
  - stage: BuildAndTest
    displayName: Build and test and publish
    jobs:
    - job: Database
      steps:
      - template: pipelines/buildAndPublishDatabase.yml
        parameters:
          BuildConfiguration: ${{ variables.buildConfiguration }}
          Artifact: database
    - job: Tests
      steps:
      - template: pipelines/buildAndPublishTests.yml
        parameters:
          BuildConfiguration: ${{ variables.buildConfiguration }}