parameters:
    BuildConfiguration: ''
    Artifact: ''

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  inputs:
    versionSpec: '5.x'

- task: UseDotNet@2
  displayName: 'Set .NET Core to 3.1'
  inputs:
    packageType: sdk
    version: 5.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Build database project'
  inputs:
    projects: '**/DreamTravelDatabase.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/Databases'
    
- publish: '$(Build.ArtifactStagingDirectory)/Databases'
  artifact: ${{ parameters.Artifact }}