steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  inputs:
    versionSpec: '5.x'

- task: UseDotNet@2
  displayName: 'Set .NET Core to 6.0'
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: PowerShell@2
  displayName: Run SQL Server
  inputs:
    targetType: 'inline'
    script: |
      docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=password_xxddd_2137' -p 1401:1433 --name DB -d mcr.microsoft.com/mssql/server:2019-latest

- task: PowerShell@2
  displayName: Deploy DB locally
  inputs:
    targetType: 'inline'
    workingDirectory: 'taleCode/TaleCodeDatabase'
    script: |
      dotnet publish /p:TargetServerName=localhost /p:TargetPort=1401 /p:TargetUser=sa /p:TargetPassword=password_xxddd_2137 /p:TargetDatabaseName=TaleCodeDatabase

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    custom: 'msbuild'
    arguments: '-p:Configuration=$(BuildConfiguration)'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish Database'
  inputs:
    projects: '**/TaleCodeDatabase.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/Databases'
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 