version: '3.7'
 
services:
    sql-server:
        container_name: sql-server
        build: 
          context: .
          dockerfile: src/TaleCodeDatabase/Dockerfile
        ports:  
          - "1403:1433"
          
    azurite:
        container_name: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
        restart: always
        command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log"
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
        volumes:
          - ./azurite:/workspace
          
    rabbit:
        container_name: rabbitmq
        image: rabbitmq:3-management
        user: rabbitmq
        ports:
          - "15672:15672"
          - "5672:5672"
        healthcheck:
          test: rabbitmq-diagnostics check_port_connectivity
          interval: 1s
          timeout: 30s
          retries: 60

    sbemulator:
        container_name: sbemulator
        image: devopsifyme/sbemu:latest
        build:
          x-bake:
            platforms:
              - "linux/arm64"
              - "linux/amd64"
          tags:
            - "devopsifyme/sbemu:latest"
            - "devopsifyme/sbemu:${TAG:-0.0.1-local}"
            - "devopsifyme/sbemu:${TAGMAJOR:-0}"
            - "devopsifyme/sbemu:${TAGMAJORMINOR:-0.0}"
            - "devopsifyme/sbemu:${TAGMAJORMINORPATCH:-0.0.1}"
          context: .
          dockerfile: ./src/ServiceBusEmulator.Host/Dockerfile
        environment:
          - EMULATOR__RABBITMQ__HOST=rabbit
          - EMULATOR__RABBITMQ__USERNAME=guest
          - EMULATOR__RABBITMQ__PASSWORD=guest
          - Emulator__ServerCertificatePath=/cert/localhost.pfx
          - Emulator__ServerCertificatePassword=password_xxddd_2137
          - Emulator__QueuesAndTopics=calculatestatistics-test;test-topic/Subscriptions/test-subscription
        ports:
          - "5671:5671"
        volumes:
          - ./tests/TaleCode.FunctionalTests/cert:/cert
        links: 
          - rabbit
        depends_on:
          rabbit:
            condition: service_healthy