variables:
 - group: talecode

 - name: BuildConfiguration
   value: 'Release'
 - name: azureServiceConnection
   value: 'azureSWO'
 - name: resourceGroupName
   value: 'TaleCode'
 - name: location
   value: 'westeurope'
 - name: templateFile
   value: 'main.bicep'

stages:
  - stage: Test
    displayName: Test
    jobs:

    - job: RunTests
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet'
        inputs:
          versionSpec: '5.x'

      - task: UseDotNet@2
        displayName: 'Set .NET Core to 6.0'
        inputs:
          packageType: sdk
          version: 6.0.x
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: PowerShell@2
        displayName: Run SQL Server
        inputs:
          targetType: 'inline'
          script: |
            docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=password_xxddd_2137' -p 1401:1433 --name DB -d mcr.microsoft.com/mssql/server:2019-latest

      - task: PowerShell@2
        displayName: Deploy DB locally
        inputs:
          targetType: 'inline'
          workingDirectory: 'taleCode/src/TaleCodeDatabase'
          script: |
            dotnet publish /p:TargetServerName=localhost /p:TargetPort=1401 /p:TargetUser=sa /p:TargetPassword=password_xxddd_2137 /p:TargetDatabaseName=TaleCodeDatabase

      - task: DotNetCoreCLI@2
        displayName: 'Run unit tests'
        inputs:
          command: 'test'
          projects: 'taleCode/**/*Tests.csproj'
          custom: 'msbuild'
          arguments: '-p:Configuration=$(BuildConfiguration)'
          publishTestResults: true


  - stage: BuildAndPublish
    displayName: Build&Publish
    jobs:

    - job: PublishArtifacts
      displayName: 'Publish Artifacts'
      steps:
        - task: CopyFiles@2
          displayName: 'Publish Infrastructure'
          inputs:
            sourceFolder: 'taleCode/devOps/infrastructure'
            contents: '*'
            targetFolder: $(Build.ArtifactStagingDirectory)/Infrastructure

        - task: DotNetCoreCLI@2
          displayName: 'Publish Database'
          inputs:
            projects: 'taleCode/**/TaleCodeDatabase.csproj'
            arguments: '-o $(Build.ArtifactStagingDirectory)/Database'
          
        - task: DotNetCoreCLI@2
          displayName: 'Publish Api'
          inputs:
            command: publish
            projects: 'taleCode/src/**/Api.csproj'
            publishWebProjects: False
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/Api'

        - task: DotNetCoreCLI@2
          displayName: 'Publish Event Listener'
          inputs:
            command: publish
            projects: 'taleCode/src/**/EventListener.csproj'
            publishWebProjects: False
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/EventListener'

        - task: FileTransform@1
          inputs:
            folderPath: '$(Build.ArtifactStagingDirectory)/**/*.zip'
            fileType: 'json'
            targetFiles: '**/appsettings.json'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)' 
            artifactName: 'drop' 
          condition: always()


  - stage: Deploy
    displayName: Deploy

    jobs: 

    - job: DeployProd
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: DownloadPipelineArtifact@2

        - task: AzureCLI@2
          displayName: 'Deploy Infrastructure'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az --version
              az group create --name $(resourceGroupName) --location $(location)
              az deployment group create \
              --resource-group $(resourceGroupName) \
              --template-file '$(Pipeline.Workspace)\drop\Infrastructure\$(templateFile)' \
              --parameters testParam='$(testParam)' baseName='taleCode' sqlAdminUserName='$(sqlAdminUserName)' sqlAdminPassword='$(sqlAdminPassword)' sqlServerName='$(sqlServerName)' databaseName='$(databaseName)' apiName='$(apiName)' storageAccountName='$(storageAccountName)' serviceBusName='$(serviceBusName)'

        - task: SqlAzureDacpacDeployment@1
          displayName: 'Deploy Database'
          inputs:
            azureSubscription: $(azureServiceConnection)
            ServerName: '$(sqlServerName).database.windows.net'
            DatabaseName: $(databaseName)
            SqlUsername: $(sqlAdminUserName)
            SqlPassword: $(sqlAdminPassword)
            DacpacFile: '$(Pipeline.Workspace)\drop\Database\TaleCodeDatabase.dacpac'

        - task: AzureWebApp@1
          displayName: 'Deploy Api'
          inputs:
            appType: webAppLinux
            azureSubscription: $(azureServiceConnection)
            appName: $(apiName)
            package: '$(Pipeline.Workspace)\drop\Api\SolTechnology.TaleCode.Api.zip'
        
        - task: AzureWebApp@1
          displayName: 'Deploy EventListener'
          inputs:
            appType: webAppLinux
            azureSubscription: $(azureServiceConnection)
            appName: $(eventListenerName)
            package: '$(Pipeline.Workspace)\drop\EventListener\SolTechnology.TaleCode.EventListener.zip'




